# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/SpookyPlayer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* Главное окно */\n"
"QMainWindow {\n"
"    background-color: #2E2E2E;\n"
"}\n"
"\n"
"/* Меню */\n"
"QMenuBar {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #66BB6A;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Списки */\n"
"QListWidget {\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* Метки */\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"/* Основной виджет */\n"
"QStackedWidget {\n"
"    background-color: #2E2E2E;\n"
"}\n"
"")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 40, 441, 401))
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, -20, 1151, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setGeometry(QtCore.QRect(30, 20, 421, 421))
        self.widget_2.setObjectName("widget_2")
        self.searchLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.searchLineEdit.setGeometry(QtCore.QRect(10, 10, 331, 31))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchButton = QtWidgets.QPushButton(self.widget_2)
        self.searchButton.setGeometry(QtCore.QRect(360, 10, 31, 31))
        self.searchButton.setObjectName("searchButton")
        self.searchResultsListWidget = QtWidgets.QListWidget(self.widget_2)
        self.searchResultsListWidget.setGeometry(QtCore.QRect(10, 50, 331, 281))
        self.searchResultsListWidget.setObjectName("searchResultsListWidget")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(680, 20, 471, 441))
        self.widget_4.setObjectName("widget_4")
        self.playlistsListWidget = QtWidgets.QListWidget(self.widget_4)
        self.playlistsListWidget.setGeometry(QtCore.QRect(0, 40, 131, 341))
        self.playlistsListWidget.setObjectName("playlistsListWidget")
        self.playlistTracksListWidget = QtWidgets.QListWidget(self.widget_4)
        self.playlistTracksListWidget.setGeometry(QtCore.QRect(160, 10, 291, 401))
        self.playlistTracksListWidget.setObjectName("playlistTracksListWidget")
        self.addPlaylistButton = QtWidgets.QPushButton(self.widget_4)
        self.addPlaylistButton.setGeometry(QtCore.QRect(0, 390, 121, 23))
        self.addPlaylistButton.setObjectName("addPlaylistButton")
        self.line_2 = QtWidgets.QFrame(self.widget_4)
        self.line_2.setGeometry(QtCore.QRect(-20, 420, 481, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.playlistTracksListWidget.raise_()
        self.playlistsListWidget.raise_()
        self.addPlaylistButton.raise_()
        self.line_2.raise_()
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(10, 460, 1131, 71))
        self.widget_5.setStyleSheet("background-color: rgba(13, 182, 197, 10);")
        self.widget_5.setObjectName("widget_5")
        self.trackInfoLabel = QtWidgets.QLabel(self.widget_5)
        self.trackInfoLabel.setGeometry(QtCore.QRect(350, 0, 421, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setBold(True)
        font.setWeight(75)
        self.trackInfoLabel.setFont(font)
        self.trackInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trackInfoLabel.setObjectName("trackInfoLabel")
        self.volumeSlider = QtWidgets.QSlider(self.widget_5)
        self.volumeSlider.setGeometry(QtCore.QRect(1070, 10, 20, 51))
        self.volumeSlider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 1px solid #bbb;\n"
"    background: rgb(48, 112, 51);\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"    margin: 0px 20px; /* Для отступа от ручки */\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: rgb(60, 139, 63);\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"    margin: 0px 20px; /* Для отступа от ручки */\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: #green;\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"    margin: 0px 20px; /* Для отступа от ручки */\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: green;\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: 0 -5px; /* Центрирование ручки по горизонтали */\n"
"    border-radius: 9px; /* Делает ручку круглой */\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background: #00ff00;\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background: #00cc00;\n"
"}\n"
"")
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setObjectName("volumeSlider")
        self.playButton = QtWidgets.QPushButton(self.widget_5)
        self.playButton.setGeometry(QtCore.QRect(550, 25, 21, 23))
        self.playButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.playButton.setObjectName("playButton")
        self.nextButton = QtWidgets.QPushButton(self.widget_5)
        self.nextButton.setGeometry(QtCore.QRect(600, 25, 21, 23))
        self.nextButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.nextButton.setObjectName("nextButton")
        self.prevButton = QtWidgets.QPushButton(self.widget_5)
        self.prevButton.setGeometry(QtCore.QRect(500, 25, 21, 23))
        self.prevButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.prevButton.setObjectName("prevButton")
        self.addTrackPlaylistButton = QtWidgets.QPushButton(self.widget_5)
        self.addTrackPlaylistButton.setGeometry(QtCore.QRect(10, 40, 171, 23))
        self.addTrackPlaylistButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.addTrackPlaylistButton.setObjectName("addTrackPlaylistButton")
        self.ProgressSlider = QtWidgets.QSlider(self.widget_5)
        self.ProgressSlider.setGeometry(QtCore.QRect(390, 50, 351, 22))
        self.ProgressSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: white;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: lightgreen;\n"
"    border: 1px solid #777;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"    border: 1px solid #777;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: lightgreen;\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: -3px 0; /* centering the handle vertically */\n"
"    border-radius: 5px; /* making it circular */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #90ee90; /* slightly lighter green */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #77dd77; /* slightly darker green */\n"
"}\n"
"")
        self.ProgressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressSlider.setObjectName("ProgressSlider")
        self.addTrackPlaylistButton_2 = QtWidgets.QPushButton(self.widget_5)
        self.addTrackPlaylistButton_2.setGeometry(QtCore.QRect(10, 10, 171, 23))
        self.addTrackPlaylistButton_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.addTrackPlaylistButton_2.setObjectName("addTrackPlaylistButton_2")
        self.trackInfoLabel2 = QtWidgets.QLabel(self.widget_5)
        self.trackInfoLabel2.setGeometry(QtCore.QRect(740, 50, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setBold(True)
        font.setWeight(75)
        self.trackInfoLabel2.setFont(font)
        self.trackInfoLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.trackInfoLabel2.setObjectName("trackInfoLabel2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(660, 10, 20, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.playlistlabel = QtWidgets.QLabel(self.centralwidget)
        self.playlistlabel.setGeometry(QtCore.QRect(680, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.playlistlabel.setFont(font)
        self.playlistlabel.setObjectName("playlistlabel")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(423, 10, 20, 431))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.searchlabel = QtWidgets.QLabel(self.centralwidget)
        self.searchlabel.setGeometry(QtCore.QRect(10, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.searchlabel.setFont(font)
        self.searchlabel.setObjectName("searchlabel")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 440, 411, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtWidgets.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        self.viewMenu = QtWidgets.QMenu(self.menubar)
        self.viewMenu.setObjectName("viewMenu")
        self.changeLangMenu = QtWidgets.QMenu(self.viewMenu)
        self.changeLangMenu.setObjectName("changeLangMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Russian = QtWidgets.QAction(MainWindow)
        self.Russian.setObjectName("Russian")
        self.Ukrainian = QtWidgets.QAction(MainWindow)
        self.Ukrainian.setObjectName("Ukrainian")
        self.English = QtWidgets.QAction(MainWindow)
        self.English.setObjectName("English")
        self.actionrussianAction = QtWidgets.QAction(MainWindow)
        self.actionrussianAction.setObjectName("actionrussianAction")
        self.actionukrainianAction = QtWidgets.QAction(MainWindow)
        self.actionukrainianAction.setObjectName("actionukrainianAction")
        self.actionenglishAction = QtWidgets.QAction(MainWindow)
        self.actionenglishAction.setObjectName("actionenglishAction")
        self.changeLangMenu.addAction(self.actionrussianAction)
        self.changeLangMenu.addAction(self.actionukrainianAction)
        self.changeLangMenu.addAction(self.actionenglishAction)
        self.viewMenu.addAction(self.changeLangMenu.menuAction())
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SpookyPlayer 2.3"))
        self.searchButton.setText(_translate("MainWindow", "🔍"))
        self.addPlaylistButton.setText(_translate("MainWindow", "Создать"))
        self.trackInfoLabel.setText(_translate("MainWindow", " "))
        self.playButton.setText(_translate("MainWindow", "⏯️"))
        self.nextButton.setText(_translate("MainWindow", "⏭️"))
        self.prevButton.setText(_translate("MainWindow", "⏮️"))
        self.addTrackPlaylistButton.setText(_translate("MainWindow", "Добавить в плейлист"))
        self.addTrackPlaylistButton_2.setText(_translate("MainWindow", "Добавить в избранное (SOON)"))
        self.trackInfoLabel2.setText(_translate("MainWindow", " "))
        self.playlistlabel.setText(_translate("MainWindow", "• Плей листы"))
        self.searchlabel.setText(_translate("MainWindow", "• Поиск"))
        self.fileMenu.setTitle(_translate("MainWindow", "Файл"))
        self.helpMenu.setTitle(_translate("MainWindow", "Помощь"))
        self.viewMenu.setTitle(_translate("MainWindow", "Вид"))
        self.changeLangMenu.setTitle(_translate("MainWindow", "Сменить язык"))
        self.Russian.setText(_translate("MainWindow", "Русский"))
        self.Ukrainian.setText(_translate("MainWindow", "Україньська"))
        self.English.setText(_translate("MainWindow", "English"))
        self.actionrussianAction.setText(_translate("MainWindow", "Russian"))
        self.actionukrainianAction.setText(_translate("MainWindow", "Ukrainian"))
        self.actionenglishAction.setText(_translate("MainWindow", "English"))
import resources_rc
