# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/SpookyPlayer/newdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 505)
        MainWindow.setMinimumSize(QtCore.QSize(350, 505))
        MainWindow.setMaximumSize(QtCore.QSize(350, 505))
        MainWindow.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spookylabel = QtWidgets.QLabel(self.centralwidget)
        self.spookylabel.setGeometry(QtCore.QRect(0, 10, 351, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.spookylabel.setFont(font)
        self.spookylabel.setStyleSheet("color: rgb(170, 0, 255);")
        self.spookylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.spookylabel.setObjectName("spookylabel")
        self.homebtn = QtWidgets.QPushButton(self.centralwidget)
        self.homebtn.setGeometry(QtCore.QRect(80, 430, 31, 31))
        self.homebtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.homebtn.setObjectName("homebtn")
        self.searchbtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchbtn.setGeometry(QtCore.QRect(160, 430, 31, 31))
        self.searchbtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.searchbtn.setObjectName("searchbtn")
        self.playlistsbtn = QtWidgets.QPushButton(self.centralwidget)
        self.playlistsbtn.setGeometry(QtCore.QRect(240, 430, 31, 31))
        self.playlistsbtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.playlistsbtn.setObjectName("playlistsbtn")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 410, 321, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 49, 341, 301))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 331, 301))
        self.widget.setStyleSheet("QListWidget {\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.search_btn = QtWidgets.QPushButton(self.widget)
        self.search_btn.setGeometry(QtCore.QRect(280, 30, 31, 31))
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.search_line = QtWidgets.QLineEdit(self.widget)
        self.search_line.setGeometry(QtCore.QRect(0, 30, 261, 31))
        self.search_line.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"}")
        self.search_line.setObjectName("search_line")
        self.search_list = QtWidgets.QListWidget(self.widget)
        self.search_list.setGeometry(QtCore.QRect(0, 80, 261, 201))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.search_list.setFont(font)
        self.search_list.setObjectName("search_list")
        self.backbtn_search = QtWidgets.QPushButton(self.widget)
        self.backbtn_search.setGeometry(QtCore.QRect(0, 0, 21, 23))
        self.backbtn_search.setStyleSheet("    QPushButton {\n"
"        background-color: rgb(58, 58, 58);\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid  rgb(58, 58, 58);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.backbtn_search.setObjectName("backbtn_search")
        self.search_label = QtWidgets.QLabel(self.widget)
        self.search_label.setGeometry(QtCore.QRect(30, 0, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        self.search_label.setFont(font)
        self.search_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_label.setObjectName("search_label")
        self.stackedWidget.addWidget(self.page)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.widget_3 = QtWidgets.QWidget(self.page_6)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 331, 301))
        self.widget_3.setObjectName("widget_3")
        self.backbtn_playlist = QtWidgets.QPushButton(self.widget_3)
        self.backbtn_playlist.setGeometry(QtCore.QRect(20, 10, 21, 23))
        self.backbtn_playlist.setStyleSheet("    QPushButton {\n"
"        background-color: rgb(58, 58, 58);\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid  rgb(58, 58, 58);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.backbtn_playlist.setObjectName("backbtn_playlist")
        self.platlist_name = QtWidgets.QLabel(self.widget_3)
        self.platlist_name.setGeometry(QtCore.QRect(40, 10, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(11)
        self.platlist_name.setFont(font)
        self.platlist_name.setAlignment(QtCore.Qt.AlignCenter)
        self.platlist_name.setObjectName("platlist_name")
        self.listtracksonplaylist = QtWidgets.QListWidget(self.widget_3)
        self.listtracksonplaylist.setGeometry(QtCore.QRect(10, 70, 311, 191))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.listtracksonplaylist.setFont(font)
        self.listtracksonplaylist.setStyleSheet("QListWidget {\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.listtracksonplaylist.setObjectName("listtracksonplaylist")
        self.deleteplaylistbtn = QtWidgets.QPushButton(self.widget_3)
        self.deleteplaylistbtn.setGeometry(QtCore.QRect(10, 270, 141, 23))
        self.deleteplaylistbtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.deleteplaylistbtn.setObjectName("deleteplaylistbtn")
        self.infoplaylist = QtWidgets.QLabel(self.widget_3)
        self.infoplaylist.setGeometry(QtCore.QRect(80, 30, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.infoplaylist.setFont(font)
        self.infoplaylist.setStyleSheet("color: rgb(255, 255, 255);")
        self.infoplaylist.setAlignment(QtCore.Qt.AlignCenter)
        self.infoplaylist.setObjectName("infoplaylist")
        self.stackedWidget.addWidget(self.page_6)
        self.homepage = QtWidgets.QWidget()
        self.homepage.setObjectName("homepage")
        self.widget_7 = QtWidgets.QWidget(self.homepage)
        self.widget_7.setGeometry(QtCore.QRect(0, 10, 321, 291))
        self.widget_7.setStyleSheet("background-color: rgb(60, 60, 60);")
        self.widget_7.setObjectName("widget_7")
        self.imgtrackmain = QtWidgets.QLabel(self.widget_7)
        self.imgtrackmain.setGeometry(QtCore.QRect(90, 50, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.imgtrackmain.setFont(font)
        self.imgtrackmain.setAlignment(QtCore.Qt.AlignCenter)
        self.imgtrackmain.setObjectName("imgtrackmain")
        self.ProgressTrackSlider = QtWidgets.QSlider(self.widget_7)
        self.ProgressTrackSlider.setGeometry(QtCore.QRect(20, 220, 281, 16))
        self.ProgressTrackSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: rgb(171, 171, 171);\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(235, 235, 235);\n"
"    border: 1px solid #777;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(171, 171, 171);\n"
"    border: 1px solid #777;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(240, 240, 240);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin: -3px 0; /* centering the handle vertically */\n"
"    border-radius: 5px; /* making it circular */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: rgb(243, 243, 243); /* slightly lighter green */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background:  rgb(255, 255, 255); /* slightly darker green */\n"
"}\n"
"")
        self.ProgressTrackSlider.setProperty("value", 48)
        self.ProgressTrackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressTrackSlider.setObjectName("ProgressTrackSlider")
        self.prevtrackbtnmain = QtWidgets.QPushButton(self.widget_7)
        self.prevtrackbtnmain.setGeometry(QtCore.QRect(110, 265, 21, 21))
        self.prevtrackbtnmain.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.prevtrackbtnmain.setObjectName("prevtrackbtnmain")
        self.pausebtnmain = QtWidgets.QPushButton(self.widget_7)
        self.pausebtnmain.setGeometry(QtCore.QRect(140, 260, 31, 31))
        self.pausebtnmain.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.pausebtnmain.setObjectName("pausebtnmain")
        self.nextbtnmain = QtWidgets.QPushButton(self.widget_7)
        self.nextbtnmain.setGeometry(QtCore.QRect(180, 265, 21, 21))
        self.nextbtnmain.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.nextbtnmain.setObjectName("nextbtnmain")
        self.btnaddtoplaylistmain = QtWidgets.QPushButton(self.widget_7)
        self.btnaddtoplaylistmain.setGeometry(QtCore.QRect(60, 260, 31, 31))
        self.btnaddtoplaylistmain.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.btnaddtoplaylistmain.setObjectName("btnaddtoplaylistmain")
        self.btnaddtoplikelistmain = QtWidgets.QPushButton(self.widget_7)
        self.btnaddtoplikelistmain.setGeometry(QtCore.QRect(220, 260, 31, 31))
        self.btnaddtoplikelistmain.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.btnaddtoplikelistmain.setObjectName("btnaddtoplikelistmain")
        self.track_name = QtWidgets.QLabel(self.widget_7)
        self.track_name.setGeometry(QtCore.QRect(20, 170, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.track_name.setFont(font)
        self.track_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.track_name.setAlignment(QtCore.Qt.AlignCenter)
        self.track_name.setObjectName("track_name")
        self.track_author = QtWidgets.QLabel(self.widget_7)
        self.track_author.setGeometry(QtCore.QRect(20, 190, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.track_author.setFont(font)
        self.track_author.setStyleSheet("color: rgb(190, 190, 190);")
        self.track_author.setAlignment(QtCore.Qt.AlignCenter)
        self.track_author.setObjectName("track_author")
        self.nowtimetrack = QtWidgets.QLabel(self.widget_7)
        self.nowtimetrack.setGeometry(QtCore.QRect(-1, 230, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.nowtimetrack.setFont(font)
        self.nowtimetrack.setStyleSheet("color: rgb(190, 190, 190);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.nowtimetrack.setAlignment(QtCore.Qt.AlignCenter)
        self.nowtimetrack.setObjectName("nowtimetrack")
        self.alltimetrack = QtWidgets.QLabel(self.widget_7)
        self.alltimetrack.setGeometry(QtCore.QRect(267, 230, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.alltimetrack.setFont(font)
        self.alltimetrack.setStyleSheet("color: rgb(190, 190, 190);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.alltimetrack.setAlignment(QtCore.Qt.AlignCenter)
        self.alltimetrack.setObjectName("alltimetrack")
        self.label_19 = QtWidgets.QLabel(self.widget_7)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgba(173, 173, 173, 160);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.playlistnamemain = QtWidgets.QLabel(self.widget_7)
        self.playlistnamemain.setGeometry(QtCore.QRect(20, 30, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.playlistnamemain.setFont(font)
        self.playlistnamemain.setStyleSheet("color: rgb(190, 190, 190);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.playlistnamemain.setAlignment(QtCore.Qt.AlignCenter)
        self.playlistnamemain.setObjectName("playlistnamemain")
        self.stackedWidget.addWidget(self.homepage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.backbtn_playlists = QtWidgets.QPushButton(self.page_2)
        self.backbtn_playlists.setGeometry(QtCore.QRect(0, 10, 21, 23))
        self.backbtn_playlists.setStyleSheet("    QPushButton {\n"
"        background-color: rgb(58, 58, 58);\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid  rgb(58, 58, 58);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.backbtn_playlists.setObjectName("backbtn_playlists")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.playlists = QtWidgets.QPushButton(self.page_2)
        self.playlists.setGeometry(QtCore.QRect(40, 40, 91, 31))
        self.playlists.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.playlists.setObjectName("playlists")
        self.likes = QtWidgets.QPushButton(self.page_2)
        self.likes.setGeometry(QtCore.QRect(200, 40, 91, 31))
        self.likes.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.likes.setObjectName("likes")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 80, 331, 211))
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stackedWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget_2.setAcceptDrops(False)
        self.stackedWidget_2.setStyleSheet("QListWidget {\n"
"    background-color: #3E3E3E;\n"
"    color: white;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.stackedWidget_2.setLineWidth(0)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 301, 181))
        self.listWidget_2.setObjectName("listWidget_2")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.scrollArea = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 301, 221))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.createplaylist = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.createplaylist.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.createplaylist.setObjectName("createplaylist")
        self.createplaylistbtn = QtWidgets.QPushButton(self.createplaylist)
        self.createplaylistbtn.setGeometry(QtCore.QRect(10, 0, 271, 41))
        self.createplaylistbtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Прозорий фон */\n"
"    border: 2px solid transparent; /* Прозора обводка по замовчуванню */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    color: white; /* Білий текст */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    font-size: 14px; /* Розмір тексту */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при наведенні */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D3D3D3; /* Повністю світліший фон при натисканні */\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при натисканні */\n"
"}\n"
"")
        self.createplaylistbtn.setObjectName("createplaylistbtn")
        self.label_6 = QtWidgets.QLabel(self.createplaylist)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.label_6.setFont(font)
        self.label_6.setAcceptDrops(False)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("QLabel {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"    border: 2px solid #E0E0E0; /* Світла обводка */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    color: white; /* Колір тексту */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при наведенні */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при натисканні */\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.createplaylist)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label_6.raise_()
        self.createplaylistbtn.raise_()
        self.playlist_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.playlist_1.setGeometry(QtCore.QRect(10, 70, 281, 51))
        self.playlist_1.setObjectName("playlist_1")
        self.playlist_btn_1 = QtWidgets.QPushButton(self.playlist_1)
        self.playlist_btn_1.setGeometry(QtCore.QRect(10, 0, 271, 41))
        self.playlist_btn_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Прозорий фон */\n"
"    border: 2px solid transparent; /* Прозора обводка по замовчуванню */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    color: white; /* Білий текст */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    font-size: 14px; /* Розмір тексту */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при наведенні */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D3D3D3; /* Повністю світліший фон при натисканні */\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при натисканні */\n"
"}\n"
"")
        self.playlist_btn_1.setObjectName("playlist_btn_1")
        self.playlist_icon_1 = QtWidgets.QLabel(self.playlist_1)
        self.playlist_icon_1.setGeometry(QtCore.QRect(10, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.playlist_icon_1.setFont(font)
        self.playlist_icon_1.setAcceptDrops(False)
        self.playlist_icon_1.setAutoFillBackground(False)
        self.playlist_icon_1.setStyleSheet("QLabel {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"    border: 2px solid #E0E0E0; /* Світла обводка */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    color: white; /* Колір тексту */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при наведенні */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при натисканні */\n"
"}\n"
"")
        self.playlist_icon_1.setObjectName("playlist_icon_1")
        self.playlist_name_1 = QtWidgets.QLabel(self.playlist_1)
        self.playlist_name_1.setGeometry(QtCore.QRect(50, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_name_1.setFont(font)
        self.playlist_name_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255, 255, 255, 0);")
        self.playlist_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.playlist_name_1.setObjectName("playlist_name_1")
        self.playlist_icon_1.raise_()
        self.playlist_name_1.raise_()
        self.playlist_btn_1.raise_()
        self.playlist_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.playlist_2.setGeometry(QtCore.QRect(10, 124, 281, 51))
        self.playlist_2.setObjectName("playlist_2")
        self.playlist_btn_2 = QtWidgets.QPushButton(self.playlist_2)
        self.playlist_btn_2.setGeometry(QtCore.QRect(10, 0, 271, 41))
        self.playlist_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Прозорий фон */\n"
"    border: 2px solid transparent; /* Прозора обводка по замовчуванню */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    color: white; /* Білий текст */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    font-size: 14px; /* Розмір тексту */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при наведенні */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D3D3D3; /* Повністю світліший фон при натисканні */\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при натисканні */\n"
"}\n"
"")
        self.playlist_btn_2.setObjectName("playlist_btn_2")
        self.playlist_icon_2 = QtWidgets.QLabel(self.playlist_2)
        self.playlist_icon_2.setGeometry(QtCore.QRect(10, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.playlist_icon_2.setFont(font)
        self.playlist_icon_2.setAcceptDrops(False)
        self.playlist_icon_2.setAutoFillBackground(False)
        self.playlist_icon_2.setStyleSheet("QLabel {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"    border: 2px solid #E0E0E0; /* Світла обводка */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    color: white; /* Колір тексту */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при наведенні */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при натисканні */\n"
"}\n"
"")
        self.playlist_icon_2.setObjectName("playlist_icon_2")
        self.playlist_name_2 = QtWidgets.QLabel(self.playlist_2)
        self.playlist_name_2.setGeometry(QtCore.QRect(50, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_name_2.setFont(font)
        self.playlist_name_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255, 255, 255, 0);")
        self.playlist_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.playlist_name_2.setObjectName("playlist_name_2")
        self.playlist_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.playlist_3.setGeometry(QtCore.QRect(10, 179, 281, 51))
        self.playlist_3.setObjectName("playlist_3")
        self.playlist_btn_4 = QtWidgets.QPushButton(self.playlist_3)
        self.playlist_btn_4.setGeometry(QtCore.QRect(10, 0, 271, 41))
        self.playlist_btn_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Прозорий фон */\n"
"    border: 2px solid transparent; /* Прозора обводка по замовчуванню */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    color: white; /* Білий текст */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    font-size: 14px; /* Розмір тексту */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при наведенні */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D3D3D3; /* Повністю світліший фон при натисканні */\n"
"    border: 2px solid #D3D3D3; /* Світло-сіра обводка при натисканні */\n"
"}\n"
"")
        self.playlist_btn_4.setObjectName("playlist_btn_4")
        self.playlist_icon_3 = QtWidgets.QLabel(self.playlist_3)
        self.playlist_icon_3.setGeometry(QtCore.QRect(10, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.playlist_icon_3.setFont(font)
        self.playlist_icon_3.setAcceptDrops(False)
        self.playlist_icon_3.setAutoFillBackground(False)
        self.playlist_icon_3.setStyleSheet("QLabel {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"    border: 2px solid #E0E0E0; /* Світла обводка */\n"
"    border-radius: 10px; /* Заокруглені краї */\n"
"    padding: 5px 10px; /* Внутрішні відступи */\n"
"    color: white; /* Колір тексту */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при наведенні */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    border: 2px solid #E0E0E0; /* Обводка залишається такою ж при натисканні */\n"
"}\n"
"")
        self.playlist_icon_3.setObjectName("playlist_icon_3")
        self.playlist_name_4 = QtWidgets.QLabel(self.playlist_3)
        self.playlist_name_4.setGeometry(QtCore.QRect(50, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_name_4.setFont(font)
        self.playlist_name_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255, 255, 255, 0);")
        self.playlist_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.playlist_name_4.setObjectName("playlist_name_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_2.addWidget(self.page_4)
        self.stackedWidget.addWidget(self.page_2)
        self.mimiplayer = QtWidgets.QWidget(self.centralwidget)
        self.mimiplayer.setGeometry(QtCore.QRect(10, 350, 321, 51))
        self.mimiplayer.setStyleSheet("background-color: rgb(60, 60, 60);")
        self.mimiplayer.setObjectName("mimiplayer")
        self.pausebtn_mini = QtWidgets.QPushButton(self.mimiplayer)
        self.pausebtn_mini.setGeometry(QtCore.QRect(190, 30, 21, 21))
        self.pausebtn_mini.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.pausebtn_mini.setObjectName("pausebtn_mini")
        self.prevbtn_mini = QtWidgets.QPushButton(self.mimiplayer)
        self.prevbtn_mini.setGeometry(QtCore.QRect(160, 30, 21, 21))
        self.prevbtn_mini.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.prevbtn_mini.setObjectName("prevbtn_mini")
        self.nextbtn_mini = QtWidgets.QPushButton(self.mimiplayer)
        self.nextbtn_mini.setGeometry(QtCore.QRect(220, 30, 21, 21))
        self.nextbtn_mini.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.nextbtn_mini.setObjectName("nextbtn_mini")
        self.track_name_mini = QtWidgets.QLabel(self.mimiplayer)
        self.track_name_mini.setGeometry(QtCore.QRect(60, 0, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.track_name_mini.setFont(font)
        self.track_name_mini.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.track_name_mini.setStyleSheet("color: rgb(197, 197, 197);")
        self.track_name_mini.setAlignment(QtCore.Qt.AlignCenter)
        self.track_name_mini.setObjectName("track_name_mini")
        self.track_time_mini = QtWidgets.QLabel(self.mimiplayer)
        self.track_time_mini.setGeometry(QtCore.QRect(40, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.track_time_mini.setFont(font)
        self.track_time_mini.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.track_time_mini.setStyleSheet("color: rgb(197, 197, 197);")
        self.track_time_mini.setAlignment(QtCore.Qt.AlignCenter)
        self.track_time_mini.setObjectName("track_time_mini")
        self.img_track_mini = QtWidgets.QLabel(self.mimiplayer)
        self.img_track_mini.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Metropolis Semi Bold")
        font.setBold(True)
        font.setWeight(75)
        self.img_track_mini.setFont(font)
        self.img_track_mini.setAlignment(QtCore.Qt.AlignCenter)
        self.img_track_mini.setObjectName("img_track_mini")
        self.addtoplaylist_mini = QtWidgets.QPushButton(self.mimiplayer)
        self.addtoplaylist_mini.setGeometry(QtCore.QRect(250, 20, 31, 31))
        self.addtoplaylist_mini.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.addtoplaylist_mini.setObjectName("addtoplaylist_mini")
        self.addtolikelist_mini = QtWidgets.QPushButton(self.mimiplayer)
        self.addtolikelist_mini.setGeometry(QtCore.QRect(286, 20, 31, 31))
        self.addtolikelist_mini.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.addtolikelist_mini.setObjectName("addtolikelist_mini")
        self.pushButton_20 = QtWidgets.QPushButton(self.mimiplayer)
        self.pushButton_20.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.pushButton_20.setStyleSheet("    QPushButton {\n"
"        background: none;\n"
"        border: 2px solid green; /* зелена обводка */\n"
"        color: #000; /* чорний колір тексту */\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background-color: #66BB6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pausebtn_mini.raise_()
        self.prevbtn_mini.raise_()
        self.nextbtn_mini.raise_()
        self.track_name_mini.raise_()
        self.img_track_mini.raise_()
        self.addtoplaylist_mini.raise_()
        self.addtolikelist_mini.raise_()
        self.pushButton_20.raise_()
        self.track_time_mini.raise_()
        self.stackedWidget.raise_()
        self.line.raise_()
        self.spookylabel.raise_()
        self.homebtn.raise_()
        self.searchbtn.raise_()
        self.playlistsbtn.raise_()
        self.line_2.raise_()
        self.mimiplayer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spookylabel.setText(_translate("MainWindow", "SpookyPlayer"))
        self.homebtn.setText(_translate("MainWindow", "🏠"))
        self.searchbtn.setText(_translate("MainWindow", "🔎"))
        self.playlistsbtn.setText(_translate("MainWindow", "📚"))
        self.search_btn.setText(_translate("MainWindow", "🔍"))
        self.backbtn_search.setText(_translate("MainWindow", "⬅️"))
        self.search_label.setText(_translate("MainWindow", "•   Поиск"))
        self.backbtn_playlist.setText(_translate("MainWindow", "⬅️"))
        self.platlist_name.setText(_translate("MainWindow", "•   Название плейлиста"))
        self.deleteplaylistbtn.setText(_translate("MainWindow", "🗑️ Удалить плейлист"))
        self.infoplaylist.setText(_translate("MainWindow", "100 треков - 4 часа"))
        self.imgtrackmain.setText(_translate("MainWindow", "картинка"))
        self.prevtrackbtnmain.setText(_translate("MainWindow", "⏮️"))
        self.pausebtnmain.setText(_translate("MainWindow", "⏸️"))
        self.nextbtnmain.setText(_translate("MainWindow", "⏭️"))
        self.btnaddtoplaylistmain.setText(_translate("MainWindow", "🔰"))
        self.btnaddtoplikelistmain.setText(_translate("MainWindow", "❤️"))
        self.track_name.setText(_translate("MainWindow", "такие флюксы льдинки"))
        self.track_author.setText(_translate("MainWindow", "Малинки малинки"))
        self.nowtimetrack.setText(_translate("MainWindow", "1:21"))
        self.alltimetrack.setText(_translate("MainWindow", "2:32"))
        self.label_19.setText(_translate("MainWindow", "Сейчас играет"))
        self.playlistnamemain.setText(_translate("MainWindow", "Плейлист {playlist_name}"))
        self.backbtn_playlists.setText(_translate("MainWindow", "⬅️"))
        self.label_4.setText(_translate("MainWindow", "•   Плэйлисты и избранное"))
        self.playlists.setText(_translate("MainWindow", "🔰"))
        self.likes.setText(_translate("MainWindow", "❤️"))
        self.createplaylistbtn.setText(_translate("MainWindow", "                                                        >"))
        self.label_6.setText(_translate("MainWindow", "➕"))
        self.label_7.setText(_translate("MainWindow", "Создать плейлист"))
        self.playlist_btn_1.setText(_translate("MainWindow", "                                                        >"))
        self.playlist_icon_1.setText(_translate("MainWindow", "🔰"))
        self.playlist_name_1.setText(_translate("MainWindow", "Название плейлиста"))
        self.playlist_btn_2.setText(_translate("MainWindow", "                                                        >"))
        self.playlist_icon_2.setText(_translate("MainWindow", "🔰"))
        self.playlist_name_2.setText(_translate("MainWindow", "Название плейлиста"))
        self.playlist_btn_4.setText(_translate("MainWindow", "                                                        >"))
        self.playlist_icon_3.setText(_translate("MainWindow", "🔰"))
        self.playlist_name_4.setText(_translate("MainWindow", "Название плейлиста"))
        self.pausebtn_mini.setText(_translate("MainWindow", "⏸️"))
        self.prevbtn_mini.setText(_translate("MainWindow", "⏮️"))
        self.nextbtn_mini.setText(_translate("MainWindow", "⏭️"))
        self.track_name_mini.setText(_translate("MainWindow", "Мэвл - Холодок "))
        self.track_time_mini.setText(_translate("MainWindow", "00:21 / 2:39"))
        self.img_track_mini.setText(_translate("MainWindow", "арт"))
        self.addtoplaylist_mini.setText(_translate("MainWindow", "🔰"))
        self.addtolikelist_mini.setText(_translate("MainWindow", "❤️"))
        self.pushButton_20.setText(_translate("MainWindow", "⏭️"))
